In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.svm import SVC

In [2]:
# Load Data
train_data = pd.read_csv("data/cup98LRN.txt", low_memory=False)
test_data = pd.read_csv("data/cup98VAL.txt", low_memory=False)
test_result = pd.read_csv("data/valtargt.txt", low_memory=False)
print('train data shape: ', train_data.shape, '\t, test_data shape: ', test_data.shape);

train data shape:  (95412, 481) 	, test_data shape:  (96367, 479)

In [ ]:
#[1:28] # demographics
#[29:42] # response to other types of mail orders
#[43:55] # overlay data
#[56:74] # donor interests
#[75] # PEP star RFA status
#[76:361] # characteristics of donor neighborhood
#[362:407] # promotion history
#[408:412] # summary variables of promotion history
#[413:456] # giving history
#[457:469] # summary variables of giving history
#[470:473] ## ID & TARGETS
#[474:479] # RFA (recency-frequency-donation amount)
#[480:481] # cluster & geocode

In [26]:
train_data.columns.values.tolist()

['ODATEDW',
 'OSOURCE',
 'TCODE',
 'STATE',
 'ZIP',
 'MAILCODE',
 'PVASTATE',
 'DOB',
 'NOEXCH',
 'RECINHSE',
 'RECP3',
 'RECPGVG',
 'RECSWEEP',
 'MDMAUD',
 'DOMAIN',
 'CLUSTER',
 'AGE',
 'AGEFLAG',
 'HOMEOWNR',
 'CHILD03',
 'CHILD07',
 'CHILD12',
 'CHILD18',
 'NUMCHLD',
 'INCOME',
 'GENDER',
 'WEALTH1',
 'HIT',
 'MBCRAFT',
 'MBGARDEN',
 'MBBOOKS',
 'MBCOLECT',
 'MAGFAML',
 'MAGFEM',
 'MAGMALE',
 'PUBGARDN',
 'PUBCULIN',
 'PUBHLTH',
 'PUBDOITY',
 'PUBNEWFN',
 'PUBPHOTO',
 'PUBOPP',
 'DATASRCE',
 'MALEMILI',
 'MALEVET',
 'VIETVETS',
 'WWIIVETS',
 'LOCALGOV',
 'STATEGOV',
 'FEDGOV',
 'SOLP3',
 'SOLIH',
 'MAJOR',
 'WEALTH2',
 'GEOCODE',
 'COLLECT1',
 'VETERANS',
 'BIBLE',
 'CATLG',
 'HOMEE',
 'PETS',
 'CDPLAY',
 'STEREO',
 'PCOWNERS',
 'PHOTO',
 'CRAFTS',
 'FISHER',
 'GARDENIN',
 'BOATS',
 'WALKER',
 'KIDSTUFF',
 'CARDS',
 'PLATES',
 'LIFESRC',
 'PEPSTRFL',
 'POP901',
 'POP902',
 'POP903',
 'POP90C1',
 'POP90C2',
 'POP90C3',
 'POP90C4',
 'POP90C5',
 'ETH1',
 'ETH2',
 'ETH3',
 'ETH4',
 'ETH5',
 'ETH6',
 'ETH7',
 'ETH8',
 'ETH9',
 'ETH10',
 'ETH11',
 'ETH12',
 'ETH13',
 'ETH14',
 'ETH15',
 'ETH16',
 'AGE901',
 'AGE902',
 'AGE903',
 'AGE904',
 'AGE905',
 'AGE906',
 'AGE907',
 'CHIL1',
 'CHIL2',
 'CHIL3',
 'AGEC1',
 'AGEC2',
 'AGEC3',
 'AGEC4',
 'AGEC5',
 'AGEC6',
 'AGEC7',
 'CHILC1',
 'CHILC2',
 'CHILC3',
 'CHILC4',
 'CHILC5',
 'HHAGE1',
 'HHAGE2',
 'HHAGE3',
 'HHN1',
 'HHN2',
 'HHN3',
 'HHN4',
 'HHN5',
 'HHN6',
 'MARR1',
 'MARR2',
 'MARR3',
 'MARR4',
 'HHP1',
 'HHP2',
 'DW1',
 'DW2',
 'DW3',
 'DW4',
 'DW5',
 'DW6',
 'DW7',
 'DW8',
 'DW9',
 'HV1',
 'HV2',
 'HV3',
 'HV4',
 'HU1',
 'HU2',
 'HU3',
 'HU4',
 'HU5',
 'HHD1',
 'HHD2',
 'HHD3',
 'HHD4',
 'HHD5',
 'HHD6',
 'HHD7',
 'HHD8',
 'HHD9',
 'HHD10',
 'HHD11',
 'HHD12',
 'ETHC1',
 'ETHC2',
 'ETHC3',
 'ETHC4',
 'ETHC5',
 'ETHC6',
 'HVP1',
 'HVP2',
 'HVP3',
 'HVP4',
 'HVP5',
 'HVP6',
 'HUR1',
 'HUR2',
 'RHP1',
 'RHP2',
 'RHP3',
 'RHP4',
 'HUPA1',
 'HUPA2',
 'HUPA3',
 'HUPA4',
 'HUPA5',
 'HUPA6',
 'HUPA7',
 'RP1',
 'RP2',
 'RP3',
 'RP4',
 'MSA',
 'ADI',
 'DMA',
 'IC1',
 'IC2',
 'IC3',
 'IC4',
 'IC5',
 'IC6',
 'IC7',
 'IC8',
 'IC9',
 'IC10',
 'IC11',
 'IC12',
 'IC13',
 'IC14',
 'IC15',
 'IC16',
 'IC17',
 'IC18',
 'IC19',
 'IC20',
 'IC21',
 'IC22',
 'IC23',
 'HHAS1',
 'HHAS2',
 'HHAS3',
 'HHAS4',
 'MC1',
 'MC2',
 'MC3',
 'TPE1',
 'TPE2',
 'TPE3',
 'TPE4',
 'TPE5',
 'TPE6',
 'TPE7',
 'TPE8',
 'TPE9',
 'PEC1',
 'PEC2',
 'TPE10',
 'TPE11',
 'TPE12',
 'TPE13',
 'LFC1',
 'LFC2',
 'LFC3',
 'LFC4',
 'LFC5',
 'LFC6',
 'LFC7',
 'LFC8',
 'LFC9',
 'LFC10',
 'OCC1',
 'OCC2',
 'OCC3',
 'OCC4',
 'OCC5',
 'OCC6',
 'OCC7',
 'OCC8',
 'OCC9',
 'OCC10',
 'OCC11',
 'OCC12',
 'OCC13',
 'EIC1',
 'EIC2',
 'EIC3',
 'EIC4',
 'EIC5',
 'EIC6',
 'EIC7',
 'EIC8',
 'EIC9',
 'EIC10',
 'EIC11',
 'EIC12',
 'EIC13',
 'EIC14',
 'EIC15',
 'EIC16',
 'OEDC1',
 'OEDC2',
 'OEDC3',
 'OEDC4',
 'OEDC5',
 'OEDC6',
 'OEDC7',
 'EC1',
 'EC2',
 'EC3',
 'EC4',
 'EC5',
 'EC6',
 'EC7',
 'EC8',
 'SEC1',
 'SEC2',
 'SEC3',
 'SEC4',
 'SEC5',
 'AFC1',
 'AFC2',
 'AFC3',
 'AFC4',
 'AFC5',
 'AFC6',
 'VC1',
 'VC2',
 'VC3',
 'VC4',
 'ANC1',
 'ANC2',
 'ANC3',
 'ANC4',
 'ANC5',
 'ANC6',
 'ANC7',
 'ANC8',
 'ANC9',
 'ANC10',
 'ANC11',
 'ANC12',
 'ANC13',
 'ANC14',
 'ANC15',
 'POBC1',
 'POBC2',
 'LSC1',
 'LSC2',
 'LSC3',
 'LSC4',
 'VOC1',
 'VOC2',
 'VOC3',
 'HC1',
 'HC2',
 'HC3',
 'HC4',
 'HC5',
 'HC6',
 'HC7',
 'HC8',
 'HC9',
 'HC10',
 'HC11',
 'HC12',
 'HC13',
 'HC14',
 'HC15',
 'HC16',
 'HC17',
 'HC18',
 'HC19',
 'HC20',
 'HC21',
 'MHUC1',
 'MHUC2',
 'AC1',
 'AC2',
 'ADATE_2',
 'ADATE_3',
 'ADATE_4',
 'ADATE_5',
 'ADATE_6',
 'ADATE_7',
 'ADATE_8',
 'ADATE_9',
 'ADATE_10',
 'ADATE_11',
 'ADATE_12',
 'ADATE_13',
 'ADATE_14',
 'ADATE_15',
 'ADATE_16',
 'ADATE_17',
 'ADATE_18',
 'ADATE_19',
 'ADATE_20',
 'ADATE_21',
 'ADATE_22',
 'ADATE_23',
 'ADATE_24',
 'RFA_2',
 'RFA_3',
 'RFA_4',
 'RFA_5',
 'RFA_6',
 'RFA_7',
 'RFA_8',
 'RFA_9',
 'RFA_10',
 'RFA_11',
 'RFA_12',
 'RFA_13',
 'RFA_14',
 'RFA_15',
 'RFA_16',
 'RFA_17',
 'RFA_18',
 'RFA_19',
 'RFA_20',
 'RFA_21',
 'RFA_22',
 'RFA_23',
 'RFA_24',
 'CARDPROM',
 'MAXADATE',
 'NUMPROM',
 'CARDPM12',
 'NUMPRM12',
 'RDATE_3',
 'RDATE_4',
 'RDATE_5',
 'RDATE_6',
 'RDATE_7',
 'RDATE_8',
 'RDATE_9',
 'RDATE_10',
 'RDATE_11',
 'RDATE_12',
 'RDATE_13',
 'RDATE_14',
 'RDATE_15',
 'RDATE_16',
 'RDATE_17',
 'RDATE_18',
 'RDATE_19',
 'RDATE_20',
 'RDATE_21',
 'RDATE_22',
 'RDATE_23',
 'RDATE_24',
 'RAMNT_3',
 'RAMNT_4',
 'RAMNT_5',
 'RAMNT_6',
 'RAMNT_7',
 'RAMNT_8',
 'RAMNT_9',
 'RAMNT_10',
 'RAMNT_11',
 'RAMNT_12',
 'RAMNT_13',
 'RAMNT_14',
 'RAMNT_15',
 'RAMNT_16',
 'RAMNT_17',
 'RAMNT_18',
 'RAMNT_19',
 'RAMNT_20',
 'RAMNT_21',
 'RAMNT_22',
 'RAMNT_23',
 'RAMNT_24',
 'RAMNTALL',
 'NGIFTALL',
 'CARDGIFT',
 'MINRAMNT',
 'MINRDATE',
 'MAXRAMNT',
 'MAXRDATE',
 'LASTGIFT',
 'LASTDATE',
 'FISTDATE',
 'NEXTDATE',
 'TIMELAG',
 'AVGGIFT',
 'CONTROLN',
 'TARGET_B',
 'TARGET_D',
 'HPHONE_D',
 'RFA_2R',
 'RFA_2F',
 'RFA_2A',
 'MDMAUD_R',
 'MDMAUD_F',
 'MDMAUD_A',
 'CLUSTER2',
 'GEOCODE2']

In [16]:
train_data.iloc[: , 0:42]

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,MAGFAML,MAGFEM,MAGMALE,PUBGARDN,PUBCULIN,PUBHLTH,PUBDOITY,PUBNEWFN,PUBPHOTO,PUBOPP
0,8901,GRI,0,IL,61081,,,3712,0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9401,BOA,1,CA,91326,,,5202,0,,...,1.0,1.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0
2,9001,AMH,1,NC,27017,,,0,0,,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,8701,BRY,0,CA,95953,,,2801,0,,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,8601,,0,FL,33176,,,2001,0,X,...,4.0,1.0,0.0,0.0,0.0,4.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,9601,ASE,1,AK,99504,,,0,0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95408,9601,DCD,1,TX,77379,,,5001,0,,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
95409,9501,MBC,1,MI,48910,,,3801,0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95410,8601,PRV,0,CA,91320,,,4005,0,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95411,8801,MCC,2,NC,28409,,,1801,0,X,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [5]:
train_data.iloc[: , 0:42]

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,MAGFAML,MAGFEM,MAGMALE,PUBGARDN,PUBCULIN,PUBHLTH,PUBDOITY,PUBNEWFN,PUBPHOTO,PUBOPP
0,8901,GRI,0,IL,61081,,,3712,0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9401,BOA,1,CA,91326,,,5202,0,,...,1.0,1.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0
2,9001,AMH,1,NC,27017,,,0,0,,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,8701,BRY,0,CA,95953,,,2801,0,,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,8601,,0,FL,33176,,,2001,0,X,...,4.0,1.0,0.0,0.0,0.0,4.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,9601,ASE,1,AK,99504,,,0,0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95408,9601,DCD,1,TX,77379,,,5001,0,,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
95409,9501,MBC,1,MI,48910,,,3801,0,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95410,8601,PRV,0,CA,91320,,,4005,0,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95411,8801,MCC,2,NC,28409,,,1801,0,X,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [27]:
train_data['CONTROLN'].describe()

count     95412.000000
mean      95778.176959
std       55284.596094
min           1.000000
25%       47910.750000
50%       95681.500000
75%      143643.500000
max      191779.000000
Name: CONTROLN, dtype: float64

In [154]:
clean_train

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,TARGET_D,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,17,342,0,19,9939,0,0,455,1,0,...,0,0,0,3,1,4,3,4,38,3
1,43,121,1,8,16857,0,0,625,1,0,...,0,0,0,1,3,4,3,4,0,1
2,21,49,1,32,335,0,0,0,1,0,...,0,1,0,3,1,4,3,4,59,3
3,9,127,0,8,18628,0,0,336,1,0,...,0,1,0,3,1,4,3,4,40,3
4,3,0,0,13,2936,0,0,240,1,1,...,0,1,0,1,2,4,3,4,25,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,52,77,1,2,19853,0,0,0,1,0,...,0,0,0,0,3,4,3,4,11,3
95408,52,233,1,48,14123,0,0,600,1,0,...,0,1,0,0,2,4,3,4,1,1
95409,46,505,1,27,6798,0,0,456,1,0,...,0,1,0,2,1,4,3,4,33,2
95410,3,666,0,8,16851,0,0,484,1,1,...,27,1,0,3,2,4,3,4,10,1
95411,14,509,2,32,878,0,0,216,1,1,...,0,1,0,0,3,0,0,0,11,3

In [118]:
header = ['ODATEDW', 'OSOURCE', 'STATE', 'ZIP', 'PVASTATE', 'DOB',
'RECINHSE', 'MDMAUD', 'DOMAIN', 'CLUSTER', 'AGE', 'HOMEOWNR',
'CHILD03', 'CHILD07', 'CHILD12', 'CHILD18', 'NUMCHLD',
'INCOME', 'GENDER', 'WEALTH1', 'HIT',
# donor interests
'COLLECT1', 'VETERANS', 'BIBLE', 'CATLG', 'HOMEE', 'PETS',
'CDPLAY', 'STEREO', 'PCOWNERS', 'PHOTO', 'CRAFTS', 'FISHER',
'GARDENIN', 'BOATS', 'WALKER', 'KIDSTUFF', 'CARDS', 'PLATES',
# PEP star RFA status
'PEPSTRFL', 
# summary variables of promotion history
'CARDPROM', 'MAXADATE', 'NUMPROM', 'CARDPM12', 'NUMPRM12',
# summary variables of giving history
'RAMNTALL', 'NGIFTALL', 'CARDGIFT', 'MINRAMNT', 'MAXRAMNT',
'LASTGIFT', 'LASTDATE', 'FISTDATE', 'TIMELAG', 'AVGGIFT',
# RFA (Recency/Frequency/Donation Amount)
'RFA_2F', 'RFA_2A', 'MDMAUD_R', 'MDMAUD_F', 'MDMAUD_A',
#others
'CLUSTER2', 'GEOCODE2']

header_new = [
    "AGE", "AVGGIFT", "CARDGIFT", "CARDPM12",
 "CARDPROM", "CLUSTER2", "DOMAIN", "GENDER", "GEOCODE2", "HIT",
 "HOMEOWNR", "HPHONE_D", "INCOME", "LASTGIFT", "MAXRAMNT",
 "MDMAUD_F", "MDMAUD_R", "MINRAMNT", "NGIFTALL", "NUMPRM12",
 "PCOWNERS", "PEPSTRFL", "PETS", "RAMNTALL", "RECINHSE",
 "RFA_2A", "RFA_2F", "STATE", "TIMELAG"
]

# pre-process data
le = LabelEncoder()
clean_train = train_data[train_data.columns[:]].apply(le.fit_transform)

clean_train = clean_train[header_new]
clean_train
X_train, X_test, y_train, y_test = train_test_split(clean_train, train_data['TARGET_B'])

In [119]:
clean_train

,AGE,AVGGIFT,CARDGIFT,CARDPM12,CARDPROM,CLUSTER2,DOMAIN,GENDER,GEOCODE2,HIT,...,NUMPRM12,PCOWNERS,PEPSTRFL,PETS,RAMNTALL,RECINHSE,RFA_2A,RFA_2F,STATE,TIMELAG
0,57,2639,14,6,26,38,11,3,3,0,...,13,0,1,0,1155,0,1,3,19,4
1,43,5344,1,6,11,0,7,5,1,16,...,12,0,0,0,127,0,3,1,8,18
2,96,2503,14,6,25,59,5,5,3,2,...,13,0,1,0,1008,0,1,3,32,12
3,67,2168,7,6,26,40,5,3,3,2,...,13,0,1,0,515,0,1,3,8,9
4,75,2193,8,10,42,25,8,3,1,60,...,24,0,0,0,1195,1,2,1,13,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,96,6596,0,5,5,11,2,5,3,0,...,11,0,0,0,33,0,3,0,2,68
95408,45,6064,0,3,3,1,1,5,1,1,...,7,0,0,0,16,0,2,0,48,68
95409,57,2886,4,7,13,33,3,5,2,0,...,16,0,1,0,179,0,1,2,27,3
95410,55,4446,18,9,35,10,1,3,1,0,...,30,0,1,0,1612,1,2,3,8,4
95411,77,7642,11,6,31,11,1,3,3,3,...,34,0,1,0,2087,1,3,0,32,6

In [75]:
clean_train

,AGE,AVGGIFT,CARDGIFT,CARDPM12,CARDPROM,CLUSTER2,DOMAIN,GENDER,GEOCODE2,HIT,...,NUMPRM12,PCOWNERS,PEPSTRFL,PETS,RAMNTALL,RECINHSE,RFA_2A,RFA_2F,STATE,TIMELAG
0,60.0,7.741935,14,6,27,39.0,11,3,3,0,...,14,0,1,0,240.0,0,1,3,19,4.0
1,46.0,15.666667,1,6,12,1.0,7,5,1,16,...,13,0,0,0,47.0,0,3,1,8,18.0
2,0.0,7.481481,14,6,26,60.0,5,5,3,2,...,14,0,1,0,202.0,0,1,3,32,12.0
3,70.0,6.812500,7,6,27,41.0,5,3,3,2,...,14,0,1,0,109.0,0,1,3,8,9.0
4,78.0,6.864865,8,10,43,26.0,8,3,1,60,...,25,0,0,0,254.0,1,2,1,13,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,0.0,25.000000,0,5,6,12.0,2,5,3,0,...,12,0,0,0,25.0,0,3,0,2,0.0
95408,48.0,20.000000,0,3,4,2.0,1,5,1,1,...,8,0,0,0,20.0,0,2,0,48,0.0
95409,60.0,8.285714,4,7,14,34.0,3,5,2,0,...,17,0,1,0,58.0,0,1,2,27,3.0
95410,58.0,12.146341,18,9,36,11.0,1,3,1,0,...,31,0,1,0,498.0,1,2,3,8,4.0
95411,80.0,96.794872,11,6,32,12.0,1,3,3,3,...,35,0,1,0,3775.0,1,3,0,32,6.0

In [93]:
def balanced_subsample(x,y,subsample_size=1.0):

    class_xs = []
    min_elems = None

    for yi in np.unique(y):
        elems = x[(y == yi)]
        class_xs.append((yi, elems))
        if min_elems == None or elems.shape[0] < min_elems:
            min_elems = elems.shape[0]

    use_elems = min_elems
    if subsample_size < 1:
        use_elems = int(min_elems*subsample_size)

    xs = []
    ys = []

    for ci,this_xs in class_xs:
        if len(this_xs) > use_elems:
            this_xs = this_xs.reindex(np.random.permutation(this_xs.index))

        x_ = this_xs[:use_elems]
        y_ = np.empty(use_elems)
        y_.fill(ci)

        xs.append(x_)
        ys.append(y_)

    xs = pd.concat(xs)
    ys = pd.Series(data=np.concatenate(ys),name='target')

    return xs,ys

In [120]:
xs,ys = balanced_subsample(X_train, y_train)

In [76]:
X_train, X_test, y_train, y_test = train_test_split(clean_train, train_data['TARGET_B'])

In [14]:
train_data['TARGET_B'] # people who donated

0        0
1        0
2        0
3        0
4        0
        ..
95407    0
95408    0
95409    0
95410    1
95411    0
Name: TARGET_B, Length: 95412, dtype: int64

In [15]:
train_data['TARGET_D'] # amount they donate

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
95407     0.0
95408     0.0
95409     0.0
95410    18.0
95411     0.0
Name: TARGET_D, Length: 95412, dtype: float64

In [16]:
train_data['TARGET_D'].describe()
# mean = 0.79
# cost = 0.68
# profit = 0.11 per person

count    95412.000000
mean         0.793073
std          4.429725
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        200.000000
Name: TARGET_D, dtype: float64

In [9]:
y_test.shape

93279     0.0
55157     0.0
48303     0.0
30741    11.0
66618     0.0
         ...
75234     0.0
71809     0.0
13240     0.0
57756     0.0
6084      0.0
Name: TARGET_D, Length: 23853, dtype: float64

In [147]:
extra_tree = ExtraTreesClassifier();
       
extra_tree.fit(X_train, y_train);
extra_result = extra_tree.predict(X_test);
print(accuracy_score(extra_result, y_test))
print_result(extra_result)

0.9491887812853729
USD	actual	predicted
total:	$19435	$0
cost:	$16220	$0
profit:	$3215	$0

In [102]:
decision_tree = DecisionTreeClassifier(max_depth = 150,
                                      min_samples_split = 3);
       
decision_tree.fit(xs, ys);
tree_result = decision_tree.predict(X_test);
print(accuracy_score(tree_result, y_test))
print_result(tree_result)

0.5310443130843081
USD	actual	predicted
count:	23853	11204
total:	$19254	$9212
cost:	$16220	$7618
profit:	$3034	$1593

In [126]:
decision_tree = make_pipeline(StandardScaler(),
                            DecisionTreeClassifier(max_depth = 150,
                                      min_samples_split = 3))
       
decision_tree.fit(xs, ys);
tree_result = decision_tree.predict(X_test);
print(accuracy_score(tree_result, y_test))
print_result(tree_result)

0.5459271370477508
USD	actual	predicted
count:	23853	10873
total:	$19754	$9769
cost:	$16220	$7393
profit:	$3534	$2375

In [127]:
linear_svc = make_pipeline(StandardScaler(),
                         LinearSVC(random_state=0, tol=1e-5, max_iter = 100000))
linear_svc.fit(xs, ys)
lsvc_result = linear_svc.predict(X_test)
print(accuracy_score(lsvc_result, y_test))
print_result(lsvc_result)

0.616987381042217
USD	actual	predicted
count:	23853	9230
total:	$19754	$7769
cost:	$16220	$6276
profit:	$3534	$1493

In [128]:
ada_tree = AdaBoostClassifier(base_estimator = decision_tree)

ada_tree.fit(X_train, y_train)

ada_result = ada_tree.predict(X_test)


print(accuracy_score(ada_result, y_test))
print_result(ada_result)

ValueError: Pipeline doesn't support sample_weight.

In [5]:
X_train

,AGE,AVGGIFT,CARDGIFT,CARDPM12,CARDPROM,CLUSTER2,DOMAIN,GENDER,GEOCODE2,HIT,...,NUMPRM12,PCOWNERS,PEPSTRFL,PETS,RAMNTALL,RECINHSE,RFA_2A,RFA_2F,STATE,TIMELAG
41854,96,3177,9,4,25,21,5,5,2,0,...,12,0,1,0,499,0,1,0,42,3
58084,45,3754,4,6,19,19,8,5,2,0,...,13,0,0,0,254,0,2,2,8,12
75038,33,5206,1,4,4,41,4,3,4,11,...,10,0,0,1,2,0,2,0,53,68
20331,48,3740,2,6,21,57,6,3,3,0,...,12,0,0,0,389,0,2,1,27,33
8386,91,340,12,2,22,40,5,5,2,1,...,8,0,1,0,174,0,1,0,27,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30155,62,7295,6,4,25,15,10,5,2,0,...,8,0,0,0,1500,0,3,0,9,13
12531,45,5825,3,5,13,37,11,3,2,0,...,11,0,0,0,162,0,2,0,27,7
9291,79,2784,8,6,22,25,3,3,1,1,...,12,0,1,0,534,0,1,1,27,3
10545,96,3655,6,4,12,16,11,5,1,0,...,7,0,0,0,639,0,2,3,14,6
19205,53,5825,3,6,13,42,8,3,2,6,...,12,0,0,1,162,0,3,0,47,15

In [24]:
X_train

,AGE,AVGGIFT,CARDGIFT,CARDPM12,CARDPROM,CLUSTER2,DOMAIN,GENDER,GEOCODE2,HIT,...,NUMPRM12,PCOWNERS,PEPSTRFL,PETS,RAMNTALL,RECINHSE,RFA_2A,RFA_2F,STATE,TIMELAG
41854,96,3177,9,4,25,21,5,5,2,0,...,12,0,1,0,499,0,1,0,42,3
58084,45,3754,4,6,19,19,8,5,2,0,...,13,0,0,0,254,0,2,2,8,12
75038,33,5206,1,4,4,41,4,3,4,11,...,10,0,0,1,2,0,2,0,53,68
20331,48,3740,2,6,21,57,6,3,3,0,...,12,0,0,0,389,0,2,1,27,33
8386,91,340,12,2,22,40,5,5,2,1,...,8,0,1,0,174,0,1,0,27,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30155,62,7295,6,4,25,15,10,5,2,0,...,8,0,0,0,1500,0,3,0,9,13
12531,45,5825,3,5,13,37,11,3,2,0,...,11,0,0,0,162,0,2,0,27,7
9291,79,2784,8,6,22,25,3,3,1,1,...,12,0,1,0,534,0,1,1,27,3
10545,96,3655,6,4,12,16,11,5,1,0,...,7,0,0,0,639,0,2,3,14,6
19205,53,5825,3,6,13,42,8,3,2,6,...,12,0,0,1,162,0,3,0,47,15

In [131]:
logistic =  make_pipeline(StandardScaler(),
                          LogisticRegression(max_iter=10000000))
logistic.fit(xs, ys)
log_result = logistic.predict(X_test)
print(accuracy_score(log_result, y_test))
print_result(log_result)

0.6158554479520396
USD	actual	predicted
count:	23853	9257
total:	$19754	$7769
cost:	$16220	$6294
profit:	$3534	$1475

In [76]:
def print_donation_amount():
    index = X_test.index
    sumDonationAmount = 0.0;
    for i in range(0, len(tree_result)):
        if (tree_result[i] == 1):
            sumDonationAmount += train_data['TARGET_B'][index[i]];
    return sumDonationAmount

In [139]:
index = X_test.index
totalDonator = 0;
predDonator = 0;
for i in range(0, len(tree_result)):
    if (train_data['TARGET_B'][index[i]] == 1):
        totalDonator+=1
    if (tree_result[i] == 1):
        predDonator+=1
print(totalDonator, ', ', predDonator)

1212 ,  1634

In [124]:
len(y_test)

23853

In [8]:
def print_result(result):
    index = X_test.index
    sumDonationAmount = 0.0;
    actualAmount = 0.0;
    predictCnt = 0
    actualCnt = len(X_test)
    for i in range(0, len(result)):
        if (result[i] == 1):
            sumDonationAmount += train_data['TARGET_D'][index[i]];
            predictCnt += 1
        if (train_data['TARGET_B'][index[i]] == 1):
            actualAmount += train_data['TARGET_D'][index[i]];



    print('USD\tactual\tpredicted')
    print('count:\t%d\t%d' % (actualCnt, predictCnt))
    predictCnt *= 0.68
    actualCnt *= 0.68
    print('total:\t$%d\t$%d' % (actualAmount, sumDonationAmount))
    print('cost:\t$%d\t$%d' % (actualCnt, predictCnt))
    print('profit:\t$%d\t$%d' % (actualAmount- actualCnt, sumDonationAmount - predictCnt))
    #return (sumDonationAmount - predictCnt)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

0.8905798012828575

In [55]:
clf = LogisticRegression(solver='lbfgs', max_iter=100000).fit(X_train, y_train)

In [56]:
result = clf.predict(X_test)

In [83]:
result.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [77]:
index = X_test.index

In [78]:
index

Int64Index([32240, 22404, 47077, 92297, 40059, 71732, 30532, 34889, 42782,
            20965,
            ...
            43774, 12607, 25131, 15460, 59362, 88201, 27215, 22049,  4557,
            83708],
           dtype='int64', length=23853)

In [60]:
X_test

,ODATEDW,OSOURCE,STATE,ZIP,PVASTATE,DOB,RECINHSE,MDMAUD,DOMAIN,CLUSTER,...,TIMELAG,AVGGIFT,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2,CONTROLN
32240,46,797,23,12213,0,348,0,27,1,22,...,68,6596,0,3,4,3,4,32,2,109713
22404,32,774,19,9946,0,294,0,27,9,21,...,4,6916,0,3,4,3,4,25,2,95574
47077,3,140,29,10779,0,0,0,27,5,43,...,14,224,3,0,4,3,4,59,4,101421
92297,21,447,41,13181,0,628,0,27,6,51,...,6,5312,0,2,4,3,4,58,4,115403
40059,27,673,29,11003,0,0,0,27,11,40,...,38,2106,3,0,4,3,4,47,3,102962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88201,17,108,41,12855,0,360,0,27,2,27,...,2,2512,0,1,4,3,4,34,2,113512
27215,43,816,47,4285,0,0,0,27,1,22,...,12,5027,2,2,4,3,4,35,2,51004
22049,32,447,19,10032,0,0,0,27,5,45,...,5,7572,0,3,4,3,4,58,4,14844
4557,14,246,48,14463,0,240,0,27,8,19,...,4,2126,1,1,4,3,4,21,2,125481
83708,3,509,19,10556,0,0,0,27,6,53,...,3,1738,2,0,4,3,4,56,4,99249

In [15]:
accuracy_score(result, y_test)

NameError: name 'result' is not defined